apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-kwvc
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-kwvc
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-kwvc
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-kwvc
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-kwvc
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-rozz-tenant/rhtap-demo-app/hacbs-test-project-kwvc@sha256:b908ea26dbeaa45cdf0bc163b2a0a103a9ad59cb4bc238671a40488ac18bdda6
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
